name: Sync Data From External Sources
on:
  schedule:
    # Every nights at 6
    - cron: "0 6 * * *"

jobs:
  sync-strings:
    runs-on: ubuntu-latest
    # Skip in forks
    if: github.repository == 'vector-im/element-x-android'
    # No concurrency required, runs every time on a schedule.
    steps:
      - uses: actions/checkout@v3
      - name: Run local script
        run: ./tools/strings/importStringsFromElement.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Import strings from Element Android
          title: Sync strings
          body: |
            - Update strings from Element Android
          branch: sync-strings
          base: develop
